web_page_archive.capture_utility.wpa_achecker_capture:
  type: mapping
  label: 'Achecker capture utility'
  mapping:
    guidelines:
      type: mapping
      mapping:
        type: string
        label: 'Guideline'

web_page_archive.wpa_achecker_capture.settings:
  type: config_object
  label: 'Achecker Capture Utility settings'
  mapping:
    defaults:
      type: mapping
      mapping:
        guidelines:
          type: mapping
          mapping:
            type: string
            label: 'Guideline'
